apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: medical-api-secrets
  namespace: default
spec:
  serviceAccountName: medical-api
  secretProviderClassName: medical-api-database-url
  secretObject:
    type: Opaque
    data:
      - sourcePath: "DATABASE_URL"
        targetKey: "DATABASE_URL"