apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: medical-api-database-url
  namespace: default
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/TU_PROJECT_ID/secrets/medical-api-database-url/versions/1"
        path: "DATABASE_URL"