apiVersion: v1
kind: ServiceAccount
metadata:
  name: medical-api
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: medical-api-gsa@project-40fc41d1-6899-4ce0-9ef.iam.gserviceaccount.com